# Generated by Django 6.0 on 2025-12-05 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True, verbose_name='ID сотрудника')),
                ('emp_code', models.CharField(max_length=20, verbose_name='Код сотрудника')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Имя сотрудника')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, verbose_name='Telegram username')),
                ('send_notifications', models.BooleanField(default=False, verbose_name='Отправлять уведомления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['emp_code'],
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.IntegerField(unique=True, verbose_name='ID терминала')),
                ('terminal_sn', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('terminal_alias', models.CharField(max_length=200, verbose_name='Название терминала')),
                ('area_alias', models.CharField(max_length=200, verbose_name='Название зоны')),
                ('is_monitored', models.BooleanField(default=True, verbose_name='Отслеживать терминал')),
            ],
            options={
                'verbose_name': 'Терминал',
                'verbose_name_plural': 'Терминалы',
                'ordering': ['terminal_alias'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skud_id', models.IntegerField(unique=True, verbose_name='ID записи в СКУД')),
                ('punch_time', models.DateTimeField(verbose_name='Время отметки')),
                ('punch_state', models.CharField(max_length=5, verbose_name='Тип отметки')),
                ('verify_type', models.IntegerField(verbose_name='Способ авторизации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.employee', verbose_name='Сотрудник')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.terminal', verbose_name='Терминал')),
            ],
            options={
                'verbose_name': 'Запись прохода',
                'verbose_name_plural': 'Записи проходов',
                'ordering': ['-punch_time'],
            },
        ),
    ]
