# Generated by Django 5.2.9 on 2026-01-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_transaction_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='emp_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Код сотрудника'),
        ),
    ]
