# Generated by Django 6.0 on 2026-01-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_transaction_emp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='auto_logout',
            field=models.BooleanField(default=False, help_text='Автоматический выход в 23:55 если сотрудник остался на пункте', verbose_name='Автоматический выход'),
        ),
    ]
